### ISSUE TITLE
unable to return newPeopleVaccinatedFirstDoseByPublishDate or newPeopleVaccinatedFirstDoseByPublishDate   

### ISSUE THREAD

**Issue by markmac99** [UKHSA-Internal/coronavirus-dashboard-api-python-sdk#33]
If either of these metrics is included in a request, the string name of the metric is returned instead of the numeric data. The equivalent for 2nd vaccine dose works correctly

For example:
structure = { 
     "date": "date",
    "name": "areaName",
    "code": "areaCode",
   "Dose1": "cumPeopleVaccinatedFirstDoseByPublishDate",
    "Dose2": "cumPeopleVaccinatedSecondDoseByPublishDate",
}
returned data is 
date,name,code,Dose1,Dose2
2021-01-13,United Kingdom,K02000001,cumPeopleVaccinatedFirstDoseByPublishDate,
2021-01-12,United Kingdom,K02000001,cumPeopleVaccinatedFirstDoseByPublishDate,428232
2021-01-11,United Kingdom,K02000001,cumPeopleVaccinatedFirstDoseByPublishDate,412167

**Comment by lirwin3007** [comment]
Just playing about, this seems to be because `Dose1` contains a number.

Doesn't work:
```
{"Dose1":"cumPeopleVaccinatedFirstDoseByPublishDate"}
```

Works:
{"Dose":"cumPeopleVaccinatedFirstDoseByPublishDate"}

**Comment by markmac99** [comment]
Interesting! 
Still looks like a bug (since "Dose2" works as a name)  but thats a useful workaround !

**Comment by markmac99** [comment]
closing as the project is abandonware
